// here is where all the data comes from (products in home page)

let productsDb = [
  {
    id: 1,
    title: 'testestoron enhancer.',
    desc: 'Lorem Ipsum Dolor, Sit Amet Consectetur Adipisicing Elit. Nisi, Eligendi.',
    seller: 'seller: verified ✓',
    imgUrl: 'img/test-enhancer.jpg',
    price: '250$',
    qty: 1,
    isMine: 'false',
  },
  {
    id: 2,
    title: 'white tiger pharma testestoron enhanthate',
    desc: 'Lorem Ipsum Dolor, Sit Amet Consectetur Adipisicing Elit. Nisi, Eligendi.',
    seller: 'seller: unverified',
    imgUrl: 'img/white-tiger-enhanthate.jpg',
    price: '330$',
    qty: 1,
    isMine: 'false',
  },
  {
    id: 3,
    title: 'white tiger pharma testestoron enhancer',
    desc: 'Lorem Ipsum Dolor, Sit Amet Consectetur Adipisicing Elit. Nisi, Eligendi.',
    seller: 'seller: verified ✓',
    imgUrl: 'img/injection-1.jpg',
    price: '226$',
    qty: 1,
    isMine: 'false',
  },
  {
    id: 4,
    title: 'iron pharma growth hormone',
    desc: 'Lorem Ipsum Dolor, Sit Amet Consectetur Adipisicing Elit. Nisi, Eligendi.',
    seller: 'seller: verified ✓',
    imgUrl: 'img/growth-hormone.jpg',
    price: '399$',
    qty: 1,
    isMine: 'false',
  },
  {
    id: 5,
    title: 'anavar oxandrolone 10mg',
    desc: 'Lorem Ipsum Dolor, Sit Amet Consectetur Adipisicing Elit. Nisi, Eligendi.',
    seller: 'seller: unverified',
    imgUrl: 'img/anavar.jpg',
    price: '250$',
    qty: 1,
    isMine: 'false',
  },
  {
    id: 6,
    title: 'd-bal 50mg',
    desc: 'Lorem Ipsum Dolor, Sit Amet Consectetur Adipisicing Elit. Nisi, Eligendi.',
    seller: 'seller: verified ✓',
    imgUrl: 'img/d-ball.jpg',
    price: '59.99$',
    qty: 1,
    isMine: 'false',
  },
  {
    id: 7,
    title: 'd-bal max 7.5mg',
    desc: 'Lorem Ipsum Dolor, Sit Amet Consectetur Adipisicing Elit. Nisi, Eligendi.',
    seller: 'seller: verified ✓',
    imgUrl: 'img/d-bal-max.jpg',
    price: '49.99$',
    qty: 1,
    isMine: 'false',
  },
  {
    id: 8,
    title: 'd-bulk',
    desc: 'Lorem Ipsum Dolor, Sit Amet Consectetur Adipisicing Elit. Nisi, Eligendi.',
    seller: 'seller: unverified',
    imgUrl: 'img/dbulk.webp',
    price: '59.99$',
    qty: 1,
    isMine: 'false',
  },
  {
    id: 9,
    title: 'testogen',
    desc: 'Lorem Ipsum Dolor, Sit Amet Consectetur Adipisicing Elit. Nisi, Eligendi.',
    seller: 'seller: unverified',
    imgUrl: 'img/testogen.jpeg',
    price: '99$',
    qty: 1,
    isMine: 'false',
  },
  {
    id: 10,
    title: 'winsol',
    desc: 'Lorem Ipsum Dolor, Sit Amet Consectetur Adipisicing Elit. Nisi, Eligendi.',
    seller: 'seller: verified ✓',
    imgUrl: 'img/winsol.jpg',
    price: '79$',
    qty: 1,
    isMine: 'false',
  },
];

// localStorage.setItem('products', JSON.stringify(productsDb));
